name: Deploy to EC2 from ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon Private ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 051826725875.dkr.ecr.ap-south-1.amazonaws.com

      - name: Decode EC2 SSH Key
        run: echo "${{ secrets.EC2_KEY }}" | base64 -d > banking-system04.pem

      - name: SSH and Deploy on EC2
        run: |
          chmod 400 banking-system04.pem
          ssh -o StrictHostKeyChecking=no -i banking-system04.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << EOF
          export HOME=/home/ec2-user
          
          # Stop and remove existing containers
           sudo docker stop frontend || true &&  sudo docker rm frontend || true
           sudo docker stop api_container || true &&  sudo docker rm api_container || true
           sudo docker stop db_container || true &&  sudo docker rm db_container || true

           aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 051826725875.dkr.ecr.ap-south-1.amazonaws.com
           
          # Pull latest images
           sudo docker pull 051826725875.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
           sudo docker pull 051826725875.dkr.ecr.ap-south-1.amazonaws.com/api:latest
           sudo docker pull 051826725875.dkr.ecr.ap-south-1.amazonaws.com/db:latest

          # Create network if not exists
           sudo docker network inspect banking-network >/dev/null 2>&1 ||  sudo docker network create banking-network

          # Run containers
           sudo docker run -d --name db_container --network banking-network -e MYSQL_ROOT_PASSWORD=Neelbera@2330 -p 3307:3306 051826725875.dkr.ecr.ap-south-1.amazonaws.com/db:latest
           sudo docker run -d --name api_container --network banking-network -p 5000:5000 051826725875.dkr.ecr.ap-south-1.amazonaws.com/api:latest
           sudo docker run -d --name frontend --network banking-network -p 80:5173 051826725875.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest

          EOF
